# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.27)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS gdcmCommon gdcmDICT gdcmDSED gdcmIOD gdcmMSFF gdcmMEXD gdcmjpeg8 gdcmjpeg12 gdcmjpeg16 gdcmexpat gdcmopenjp2 gdcmcharls gdcmzlib gdcmuuid socketxx vtkgdcm)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target gdcmCommon
add_library(gdcmCommon SHARED IMPORTED)

set_target_properties(gdcmCommon PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr"
)

# Create imported target gdcmDICT
add_library(gdcmDICT SHARED IMPORTED)

# Create imported target gdcmDSED
add_library(gdcmDSED SHARED IMPORTED)

set_target_properties(gdcmDSED PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_strong_enums"
  INTERFACE_LINK_LIBRARIES "gdcmCommon"
)

# Create imported target gdcmIOD
add_library(gdcmIOD SHARED IMPORTED)

set_target_properties(gdcmIOD PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmDSED;gdcmCommon"
)

# Create imported target gdcmMSFF
add_library(gdcmMSFF SHARED IMPORTED)

set_target_properties(gdcmMSFF PROPERTIES
  INTERFACE_LINK_LIBRARIES "gdcmIOD;gdcmDSED;gdcmDICT"
)

# Create imported target gdcmMEXD
add_library(gdcmMEXD SHARED IMPORTED)

# Create imported target gdcmjpeg8
add_library(gdcmjpeg8 SHARED IMPORTED)

# Create imported target gdcmjpeg12
add_library(gdcmjpeg12 SHARED IMPORTED)

# Create imported target gdcmjpeg16
add_library(gdcmjpeg16 SHARED IMPORTED)

# Create imported target gdcmexpat
add_library(gdcmexpat SHARED IMPORTED)

# Create imported target gdcmopenjp2
add_library(gdcmopenjp2 SHARED IMPORTED)

set_target_properties(gdcmopenjp2 PROPERTIES
  INTERFACE_LINK_LIBRARIES "m;-lpthread"
)

# Create imported target gdcmcharls
add_library(gdcmcharls SHARED IMPORTED)

set_target_properties(gdcmcharls PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_strong_enums"
)

# Create imported target gdcmzlib
add_library(gdcmzlib SHARED IMPORTED)

# Create imported target gdcmuuid
add_library(gdcmuuid SHARED IMPORTED)

# Create imported target socketxx
add_library(socketxx SHARED IMPORTED)

set_target_properties(socketxx PROPERTIES
  INTERFACE_COMPILE_FEATURES "cxx_nullptr"
)

# Create imported target vtkgdcm
add_library(vtkgdcm SHARED IMPORTED)

set_target_properties(vtkgdcm PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/home/majd/Software/GDCM/GDCM-build/Utilities/VTK;/home/majd/Software/GDCM/Utilities/VTK"
  INTERFACE_LINK_LIBRARIES "VTK::CommonCore;VTK::CommonDataModel;VTK::CommonExecutionModel;VTK::IOImage;VTK::IOLegacy;VTK::ImagingSources"
)

# Import target "gdcmCommon" for configuration ""
set_property(TARGET gdcmCommon APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmCommon PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmCommon.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmCommon.so.3.1"
  )

# Import target "gdcmDICT" for configuration ""
set_property(TARGET gdcmDICT APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmDICT PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "gdcmDSED;gdcmIOD"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmDICT.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmDICT.so.3.1"
  )

# Import target "gdcmDSED" for configuration ""
set_property(TARGET gdcmDSED APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmDSED PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "gdcmzlib"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmDSED.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmDSED.so.3.1"
  )

# Import target "gdcmIOD" for configuration ""
set_property(TARGET gdcmIOD APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmIOD PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "gdcmexpat"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmIOD.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmIOD.so.3.1"
  )

# Import target "gdcmMSFF" for configuration ""
set_property(TARGET gdcmMSFF APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmMSFF PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "gdcmjpeg8;gdcmjpeg12;gdcmjpeg16;gdcmopenjp2;gdcmcharls;gdcmuuid"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmMSFF.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmMSFF.so.3.1"
  )

# Import target "gdcmMEXD" for configuration ""
set_property(TARGET gdcmMEXD APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmMEXD PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "gdcmMSFF;gdcmDICT;gdcmDSED;gdcmIOD;socketxx"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmMEXD.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmMEXD.so.3.1"
  )

# Import target "gdcmjpeg8" for configuration ""
set_property(TARGET gdcmjpeg8 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmjpeg8 PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmjpeg8.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmjpeg8.so.3.1"
  )

# Import target "gdcmjpeg12" for configuration ""
set_property(TARGET gdcmjpeg12 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmjpeg12 PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmjpeg12.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmjpeg12.so.3.1"
  )

# Import target "gdcmjpeg16" for configuration ""
set_property(TARGET gdcmjpeg16 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmjpeg16 PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmjpeg16.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmjpeg16.so.3.1"
  )

# Import target "gdcmexpat" for configuration ""
set_property(TARGET gdcmexpat APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmexpat PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmexpat.so.2.0.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmexpat.so.2.0"
  )

# Import target "gdcmopenjp2" for configuration ""
set_property(TARGET gdcmopenjp2 APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmopenjp2 PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmopenjp2.so.2.3.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmopenjp2.so.7"
  )

# Import target "gdcmcharls" for configuration ""
set_property(TARGET gdcmcharls APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmcharls PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmcharls.so.2.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmcharls.so.2"
  )

# Import target "gdcmzlib" for configuration ""
set_property(TARGET gdcmzlib APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmzlib PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmzlib.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmzlib.so.3.1"
  )

# Import target "gdcmuuid" for configuration ""
set_property(TARGET gdcmuuid APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(gdcmuuid PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libgdcmuuid.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libgdcmuuid.so.3.1"
  )

# Import target "socketxx" for configuration ""
set_property(TARGET socketxx APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(socketxx PROPERTIES
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libsocketxx.so.1.2.0"
  IMPORTED_SONAME_NOCONFIG "libsocketxx.so.1.2"
  )

# Import target "vtkgdcm" for configuration ""
set_property(TARGET vtkgdcm APPEND PROPERTY IMPORTED_CONFIGURATIONS NOCONFIG)
set_target_properties(vtkgdcm PROPERTIES
  IMPORTED_LINK_DEPENDENT_LIBRARIES_NOCONFIG "VTK::CommonMisc;VTK::ImagingCore;VTK::IOCore;VTK::InteractionStyle;VTK::RenderingCore;gdcmMSFF"
  IMPORTED_LOCATION_NOCONFIG "/home/majd/Software/GDCM/GDCM-build/bin/libvtkgdcm-9.3.so.3.1.0"
  IMPORTED_SONAME_NOCONFIG "libvtkgdcm-9.3.so.1"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
